paxlingua_phrases = {
    "Where are you from?": {
        "Paxlingua": "Ubikas estuyo ex?",
        "Shorthand Paxlingua": "Ubkestx?",
        "English": "Where are you from?",
        "Semantic Field": "Personal Information",
        "Phrase Breakdown": [
            {
                "Origins": ["Latin", "Hungarian", "Arabic", "Japanese"],
                "Word": "Ubikas",
                "Translation": "Where",
                "Synonyms": ["Ubiqa", "Yerka"],
                "Antonyms": ["Neubikas"],
                "Etymology": "Derived from 'ubi' in Latin, 'hol' in Hungarian, 'أين (ayn)' in Arabic, and 'どこ (doko)' in Japanese.",
                "LUS Estimate": 0.8867,
                "Pronunciation": "/ˈjuːbɪkəs/",
                "Shorthand Paxlingua": "Ubk",
                "Usage Examples": ["Ubikas estuyo?", "Ubikas paxlomundo?"],
            },
            {
                "Origins": ["English", "French", "Russian", "Turkish"],
                "Word": "estuyo",
                "Translation": "are you",
                "Synonyms": ["etes-tu", "vy-est"],
                "Antonyms": ["nonestuyo"],
                "Etymology": "Combination of 'are' in English, 'êtes' in French, 'есть (yest)' in Russian, and 'sen' in Turkish with possessive suffix 'tuyo' derived from Spanish 'tuyo'.",
                "LUS Estimate": 0.9056,
                "Pronunciation": "/ɛsˈtujoʊ/",
                "Shorthand Paxlingua": "est",
                "Usage Examples": ["Estuyo malumo?", "Komas estuyo?"],
            },
            {
                "Origins": ["English", "Greek", "Hebrew", "Korean"],
                "Word": "ex",
                "Translation": "from",
                "Synonyms": ["ek", "mey"],
                "Antonyms": ["neex"],
                "Etymology": "Derived from 'ex' in English and Latin, 'από (apó)' in Greek, 'מ (me)' in Hebrew, and '에서 (eseo)' in Korean.",
                "LUS Estimate": 0.8815,
                "Pronunciation": "/ɛks/",
                "Shorthand Paxlingua": "ex",
                "Usage Examples": ["Ex paxlomundo?", "Ubikas estuyo ex?"],
            },
        ],
        "Grammar Rules": {
            "SVO word order": True,
            "No noun gender": True,
            "Agglutinative language": True,
            "Verb prefixes for tense": False,
            "No irregular verbs": True,
            "Prepositions": True,
        },
    },
}

